from setuptools import setup, find_packages, Extension
setup(name='Mars',      
version='1.2.1',      
description='Multiple Alignment-based Refinement of SVs',      
author='Xin Zhou',      
author_email='maizie.zhou@vanderbilt.edu',      
install_requires=['pysam','pandas','minimap2','openpyxl','samtools'],         
license='MIT',      
packages=['bin',],
package_data={'bin' : ['paftools/paftools.js',
                     'k8-0.2.4/k8-Darwin',
                       'k8-0.2.4/k8-Linux',
                       'k8-0.2.4/k8.cc',
                       'k8-0.2.4/k8.js',
                       'k8-0.2.4/khash.h',
                     'trf_tools/trf',
                     ]},  
entry_points={'console_scripts':['MARS_step1=bin.MARS_step1:main',
'MARS_step2=bin.MARS_step2:main'
               ]},
zip_safe=False)
